# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "Alfresco"
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "6144"
    vb.cpus = 2

    if ! File.file?('data_disk.vdi') then
      vb.customize ['createhd', '--filename', 'data_disk', '--size', 102400]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SCSI Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', 'data_disk.vdi'] 
  end

  config.vm.provision "shell", path: "provision.sh"
  config.vm.network "public_network",
        use_dhcp_assigned_default_route: true,
        :mac => "02"+String(Digest::MD5.hexdigest `ls -1 -i #{__FILE__}`).slice(1, 10),
        :bridge => `ip link list | grep -viE 'link|loopback' | grep -E '\\bstate UP\\b' | head -n 1 | perl -pe 's/^.*?\\s(\\S*):.*\n$/$1/'`

end
